apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: moderation
  template:
    metadata:
      labels: 
        app: moderation 
    spec:
      containers: 
        - name: moderation 
          image: sweez1968/moderation:latest
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-cluster-ip-srvc
spec:
  selector:
    app: moderation
  type: ClusterIP 
  ports:
    - port: 4300
      targetPort: 4300
      protocol: TCP
      name: moderation 