apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template: 
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: sweez1968/event-bus:latest
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srvc
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
    - name: event-bus
      protocol: TCP
      port: 4500
      targetPort: 4500



