apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments  
          image: sweez1968/comments:latest
---
apiVersion: v1
kind: Service
metadata:
  name: comments-cluster-ip-srvc
spec:
  selector:
    app: comments
  type: ClusterIP
  ports:
    - port: 4100
      targetPort: 4100
      protocol: TCP
      name: comments

