apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec: 
     containers:
      - name: query
        image: sweez1968/query:latest
---
apiVersion: v1
kind: Service
metadata:
  name: query-cluster-ip-srvc 
spec: 
  selector:
    app: query
  type: ClusterIP
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
      name: query 